local env = require("environment")
local Stopwatch = require("system/Stopwatch")

describe("Stopwatch", function ()
    env.Prepare()
    it("Can start, stop, reset stopwatch", function ()
        local sw = Stopwatch.New()
        assert.are_equal(0, sw:Elapsed())
        assert.is_false(sw:IsRunning())

        sw:Start()
        assert.is_true(sw:IsRunning())
        assert.is_true(sw:Elapsed() > 0)
        sw:Restart()
        assert.is_true(sw:IsRunning())
        assert.is_true(sw:Elapsed() > 0)
        sw:Stop()
        assert.is_false(sw:IsRunning())
        assert.is_true(sw:Elapsed() > 0)
        sw:Start()
        assert.is_true(sw:IsRunning())
        assert.is_true(sw:Elapsed() > 0)
        sw:Reset()
        assert.is_false(sw:IsRunning())
        assert.are_equal(0, sw:Elapsed())
    end)
end)