---@enum Keys
local keys = {
    lshift = 1,
    lalt = 2,
    brake = 3,
    forward = 4,
    backward = 5,
    yawleft = 6,
    yawright = 7,
    strafeleft = 8,
    straferight = 9,
    left = 10,
    right = 11,
    up = 12,
    down = 13,
    groundaltitudeup = 14,
    groundaltitudedown = 15,
    gear = 16,
    light = 17,
    stopengines = 18,
    speedup = 19,
    speeddown = 20,
    antigravity = 21,
    booster = 22,
    option1 = 23,
    option2 = 24,
    option3 = 25,
    option4 = 26,
    option5 = 27,
    option6 = 28,
    option7 = 29,
    option8 = 30,
    option = 31
}

return keys
